### ISSUE TITLE
saving large outputs

### ISSUE THREAD

**Issue by mhbodell** [ninpnin/probabilistic-word-embeddings#6]
Trying to save output (e) from "largeish" dynamic model with: e.save(file_name) generate error code: 

OverflowError: cannot serialize a bytes object larger than 4 GiB

Suggested solution: change line 108 in probabilistic-word-embeddings/probabilistic_word_embeddings/embeddings.py to "pickle.dump(d, f, protocol = 4)"

----
Python 3.7.6
Ubuntu 20.04.5 LTS

**Comment by ninpnin** [comment]
Fixed in [v0.14.1](https://github.com/ninpnin/probabilistic-word-embeddings/releases/tag/v0.14.1) !
